apiVersion: v1
kind: Secret
metadata:
  name: pod-1-secret
type: Opaque
data:
  KEY_ONE: U2VjcmV0

---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-1
  namespace: default
  labels:
    app: nginx
spec:
  containers:
  - image: snowleopardmeowmeow/0527hw-nginx-image:0.1
    imagePullPolicy: Always
    name: nginx-pod-1
    ports:
      - containerPort: 80
        protocol: TCP
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: pod-1-secret-volume
  volumes:
  - name: pod-1-secret-volume
    secret:
      secretName: pod-1-secret
      items:
      - key: KEY_ONE
        path: index.html
