apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-3
  namespace: default
spec:
  containers:
  - image: snowleopardmeowmeow/0527hw-nginx-image:0.1
    imagePullPolicy: Always
    name: nginx
    resources:
      requests:
        memory: "100Mi"
        cpu: "100m"
      limits:
        memory: "100Mi"
        cpu: "100m"
    ports:
      - containerPort: 80
        protocol: TCP
