apiVersion: v1
kind: ConfigMap
metadata:
  name: pod-2-config
data:
  KEY_ONE: Config

---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-2
  namespace: default
  labels:
    app: nginx
spec:
  containers:
  - image: snowleopardmeowmeow/0527hw-nginx-image:0.1
    imagePullPolicy: Always
    name: nginx-pod-2
    ports:
      - containerPort: 80
        protocol: TCP
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: pod-2-config-volume
      readOnly: true
  volumes:
  - name: pod-2-config-volume
    configMap:
      name: pod-2-config
      items:
        - key: KEY_ONE
          path: index.html
